name: testdocs

on: [push, pull_request]

jobs:
  check_docstrings:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run docstring check
        run: python utils/check_docstrings.py